### ISSUE TITLE
Feature: remember last selected extension and username in TER upload form

### ISSUE THREAD

**Issue by liayn** [kaystrobach/TYPO3.developer#15]

**Comment by kaystrobach** [comment]
ok, but i will never store the password, like TYPO3 4.5 :smile:

**Comment by kaystrobach** [comment]
@liayn how long would you like to have that saved? in the be_user config forever or just in the session?

**Comment by liayn** [comment]
uc

**Comment by kaystrobach** [comment]
@me http://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/BackendUserObject/Index.html#be-user-module-save

**Comment by kaystrobach** [comment]
change is now in git master!
