### ISSUE TITLE
TER upload: Linebreaks for upload comments are wrong

### ISSUE THREAD

**Issue by liayn** [kaystrobach/TYPO3.developer#16]
Checkout this: http://typo3.org/extensions/repository/view/rx_shariff (version 1.1)
There should be two list items.

Looks like the LF encoding is not sufficient.

**Comment by kaystrobach** [comment]
accepted, thank you a lot for reporting!

**Comment by kaystrobach** [comment]
@liayn IMHO the transfer was correct, but the formatting of the output on TYPO3.org is wrong.

![2015-02-26_16-00-27](https://cloud.githubusercontent.com/assets/1185776/6394274/b84180a2-bdd0-11e4-9edd-4368142e6407.png)

**Comment by liayn** [comment]
Thanks
