### ISSUE TITLE
xlf generated files

### ISSUE THREAD

**Issue by rewebit** [kaystrobach/TYPO3.developer#18]
Thank you for the XML to XLF converter feature. One small adjustment which would make it a little nicer, is to have the language code prepended to the front of the file. Being new to TYPO3 language files, I did not know the naming convention and when reimporting the translated files, ran into problems.

Instead of building the following from locallang.xml:
locallang.ja.xlf
locallang.xlf

These would be built:
ja.locallang.xlf
locallang.xlf

Thanks again for the functionality, has been a big help.
Robert

**Comment by kaystrobach** [comment]
could you please verify the linked pull request? if it works for you i will merge it.

**Comment by liayn** [comment]
I can recommend the conversion feature of lfeditor. The extension sole purpose is language handling, while this one's is more open.

**Comment by kaystrobach** [comment]
@liayn thank you, will add a hint on that extension to the tools and to the conversion page

**Comment by rewebit** [comment]
Hello Kay,

The fix works. Thanks!

Kind Regards,
Robert
