### ISSUE TITLE
Feature: TCA Validator

### ISSUE THREAD

**Issue by liayn** [kaystrobach/TYPO3.developer#24]
Implement a module, which checks the whole TCA for validity.

e.g. if enableFields are really present, if type field is present, etc.

**Comment by kaystrobach** [comment]
Will you add a pull request ;)

**Comment by liayn** [comment]
No, sorry. Just posted this as idea here, since we ran into invalid TCA in the Core today. Since this is a pure development feature, I didn't suggest it on Forge and thought it would well fit here.
