### ISSUE TITLE
Feature: Diff/Modified files listing of local exts vs TER version x.y

### ISSUE THREAD

**Issue by liayn** [kaystrobach/TYPO3.developer#9]
A tool to see local modifications of extensions in comparison to the TER version.
Let the user select the version number of the TER version.

First step it would suffice to see whether there's a modification at all.

**Comment by kaystrobach** [comment]
anyway this is rather complex, we would need to

* download the t3x file
* extract it to the temp folder
* check all files of (existence and changes)

So showing, which files are changed is quite easy, after all the other stuff ;)

**Comment by kaystrobach** [comment]
![2015-07-08_16-52-11](https://cloud.githubusercontent.com/assets/1185776/8573427/c044793e-2591-11e5-864b-dc2d364978dd.png)
